/** Declaration file generated by dts-gen */

export = Block

declare class Block {
  header: any
  _common: any
  transactions: any[]
  uncleHeaders: any[]
  raw: any
  constructor(data?: any, opts?: any)

  genTxTrie(cb: any): void

  hash(): any

  isGenesis(): any

  serialize(rlpEncode: any): any

  setGenesisParams(): void

  toJSON(labeled: any): any

  validate(blockChain: any, cb: any): void

  validateTransactions(stringError: any): any

  validateTransactionsTrie(): any

  validateUncles(blockChain: any, cb: any): any

  validateUnclesHash(): any
}

declare namespace Block {
  class Header {
    _common: any
    raw: any
    number: any
    difficulty: any
    parentHash: any

    constructor(data?: any, opts?: any)

    canonicalDifficulty(parentBlock: any): any

    hash(): any

    isGenesis(): any

    setGenesisParams(): void

    validate(blockchain: any, height: any, cb?: any, ...args: any[]): any

    validateDifficulty(parentBlock: any): any

    validateGasLimit(parentBlock: any): any
  }
}
